### ISSUE TITLE
Missing dependencies in v1.3.0 release

### ISSUE THREAD

**Issue by OldSneerJaw** [isbang/compose-action#12]
When using the [v1.3.0](https://github.com/isbang/compose-action/releases/tag/v1.3.0) release in a workflow, I get the following error:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/isbang/compose-action/v1.3.0/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/isbang/compose-action/v1.3.0/main.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/isbang/compose-action/v1.3.0/main.js' ]
}
```

I believe the `@actions/core`, `@actions/github` and `docker-compose` packages should be moved out of `package.json`'s `devDependencies` section and into the `dependencies` section so they are available at runtime.

**Comment by isbang** [comment]
@OldSneerJaw  Cloud you please check if this issue has been fixed by [v1.3.1](https://github.com/isbang/compose-action/releases/tag/v1.3.1)?

**Comment by OldSneerJaw** [comment]
@isbang No luck. After skimming the GitHub Actions [docs](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github), it appears you'll have to either commit the `node_modules` directory to the repo or, ideally, use [@vercel/ncc](https://github.com/vercel/ncc).

**Comment by isbang** [comment]
Let me revert https://github.com/isbang/compose-action/commit/abbea8994fd882508d2c72268cebad2be9967b9c commit. I hope this will fix the problem.

**Comment by isbang** [comment]
@OldSneerJaw Hope [v1.3.2](https://github.com/isbang/compose-action/releases/tag/v1.3.2) fixed this problem. How is it now?

**Comment by OldSneerJaw** [comment]
It works again. Thanks!
